name: Pull Request

on:
  push:
    branches: ["develop", "master"]
  pull-request:
    branches: ["develop", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: |
        npm ci
        npm run test